language: c
dist: bionic # 默认为 gcc7.4, clang 7.0

addons:
  apt:
    sources:
    - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main'
      key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
# 无法手动只把源添加到list里，否则：
# Err:7 http://apt.llvm.org/stretch llvm-toolchain-stretch-8 InRelease
#   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 15CF4D18AF4F7421
# Reading package lists... Done
# W: GPG error: http://apt.llvm.org/stretch llvm-toolchain-stretch-8 InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 15CF4D18AF4F7421
# E: The repository 'http://apt.llvm.org/stretch llvm-toolchain-stretch-8 InRelease' is not signed.
# N: Updating from such a repository can't be done securely, and is therefore disabled by default.
# N: See apt-secure(8) manpage for repository creation and user configuration details.

# 官方的教程安装gcc9，实际完全无效
# addons:
#   apt:
#     sources:
#     - ubuntu-toolchain-r-test
#     - sourceline: 'ppa:ubuntu-toolchain-r/test'
#     update: true
#   packages:
#     - gcc-9

# 用于matrix测试
# compiler:
#   - gcc
#   - clang

notifications:
  email: false

before_install:
  # - echo "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-8 main" | sudo tee -a /etc/apt/sources.list
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install -y gcc-9 clang-8

# http://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html
# pointer-compare,pointer-subtract 是gcc8引入的，要么不加，要么用新版；clang8直接不支持
script:
 - gcc-9 -fsyntax-only -Wall -Wextra -DTRAVIS -fsanitize=undefined,address,leak,pointer-compare,pointer-subtract **/*.c
 - clang-8 -fsyntax-only -Wall -Wextra -DTRAVIS -fsanitize=undefined,address,leak **/*.c
