name: Lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run: |
        clang -fsyntax-only -Wall -Werror -std=gnu2x *.c **/*.c;
        clang -c --analyze -fsanitize=undefined -Werror -std=gnu2x *.c **/*.c;
        # 运行时才生效的debug手段
        # gcc -fsanitize=undefined,address,leak,pointer-compare,pointer-subtract *.c **/*.c;
        # clang没有pointer-compare,pointer-subtract，但有memory；gcc的undefined是runtime的
